### ISSUE TITLE
SPI baudrate

### ISSUE THREAD

**Issue by peterhinch** [adafruit/Adafruit_CircuitPython_ILI9341#24]
In your [instructions page](https://learn.adafruit.com/adafruit-2-8-and-3-2-color-tft-touchscreen-breakout-v2/python-usage) your code sets the baudrate to 24MHz. Yet your [ILI9341 datasheet](http://www.adafruit.com/datasheets/ILI9341.pdf) P231 section 19.3.4 specifies a minimum clock cycle time of 100ns for write cycles.

I have written a driver to enable my [MicroPython nano-gui](https://github.com/peterhinch/micropython-nano-gui) to work with your ILI9341 displays. I am reluctant to recommend an overclock without some justification. I have a high regard for your company's engineering skills and am sure you wouldn't risk a support nightmare so please could you explain the justification as 10MHz really is rather slow.

FWIW my board works fine at 40MHz...

**Comment by ladyada** [comment]
if you are unsure, make the default freq 10mhz and folks could try running it faster. its your code 😁
