### ISSUE TITLE
How to adapt ILI9341 to drive the ILI9488 ?

### ISSUE THREAD

**Issue by renejeanmercier** [adafruit/Adafruit_CircuitPython_ILI9341#36]
Hi,

Is there a way or an already adaptation of the ILI9341.py to drive an ILI9488, 3.5 inch TFT ?

Thank you for your help.

Regards,

RJM

**Comment by makermelissa** [comment]
Most likely yes. The TFT drivers generally have the init codes for the display, which you'll need to get as well as the specific parameters to pass into CircuitPython. This is likely a good one to use as a starting point.

**Comment by renejeanmercier** [comment]
Hi Melissa, 

I read and understood the protocol used in the __init__ file for the ILI9341.py. I compared the ILITEK ILI9488 datasheet with the ILILTEK ILI9341 datasheet to see the differences. From there I tried to port github  Jarret Burkett ILI9488 (C++) parameters without success. I did the same with the Bodmer ILI9488 parameters without success. (...Bodmer ILI9488 is a driver that I often use  with success all the time when I program in C++). I believe that there are subtleties in the circuitpython driver that (1) I either not completely understand or (2) are going further than the simple parameters transposition.

Would you mind ...PLEASE asking someone in your organization (may be the person that produced the ILI9341 driver)  to add such driver to your driver palette? I have been using the TFT 3.5 inch ILI9488 controller since a few years and I believe it is the perfect size for small projects and for that it should be in your palette of offering.

Please do something about that, so that I can use circuitpython in my design, ...circuitpython have so much to offer to the designers and hobbyists.

Regards, RJM
